name: 'Pipeline CI/CD'

on:
  push:
  workflow_dispatch:

jobs:
  lint:
    name: Lint (ESLint)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - run: npm run lint

  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - run: npm run test:unit

  build:
    name: Build & Archive Docker Image
    runs-on: ubuntu-latest
    needs:
      - lint
      - unit_tests
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kolos:${{ github.sha }},${{ secrets.DOCKERHUB_USERNAME }}/kolos:latest
          load: true
          push: false
      - run: docker save ${{ secrets.DOCKERHUB_USERNAME }}/kolos:${{ github.sha }} -o image.tar
      - uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar

  deploy_staging:
    name: Deploy Staging (manual approval to prod)
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    environment:
      name: staging
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: docker-image
      - run: echo ">>> Symulacja: obraz wdrożony na staging."
      - run: echo ">>> Użytkownik decyduje czy wdrażać na produkcję."

  approve_production:
    name: Approve Production Deploy
    runs-on: ubuntu-latest
    needs: deploy_staging
    if: github.ref == 'refs/heads/master'
    environment:
      name: production
      # Manual approval required in GitHub UI for prod environment
    steps:
      - run: echo "Manual approval for production deploy. Jeśli zatwierdzisz, ruszy deploy_production."

  deploy_production:
    name: Deploy Production
    runs-on: ubuntu-latest
    needs: approve_production
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: docker-image
      - uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker load -i image.tar
      - run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/kolos:${{ github.sha }}
      - run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/kolos:latest

  final_report:
    name: Final Report
    runs-on: ubuntu-latest
    needs:
      - build
      - deploy_staging
      - deploy_production
    if: always()
    steps:
      - name: Generate simple report
        run: |
          echo "==== Pipeline Report ====" > raport.txt
          echo "Lint: ${{ needs.build.result }}" >> raport.txt
          echo "Unit Tests: ${{ needs.unit_tests.result }}" >> raport.txt
          echo "Build: ${{ needs.build.result }}" >> raport.txt
          echo "Deploy Staging: ${{ needs.deploy_staging.result }}" >> raport.txt
          echo "Deploy Production: ${{ needs.deploy_production.result }}" >> raport.txt
      - name: Upload pipeline report
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-report
          path: raport.txt
